In [1]:
import pandas as pd

In [2]:
#df = pd.read_excel("./25-26Fall.xlsx")
df = pd.read_excel("./UBF_course_data_RAW.xlsx")
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
129,Yönetim Bilişim Sistemleri (İÖ),YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,63
130,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,24
131,Yönetim Bilişim Sistemleri (İÖ),YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,31
132,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,59
133,Yönetim Bilişim Sistemleri (İÖ),YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,62

In [3]:
df.drop(index=df[df['KREDI'] == 0].index, inplace=True)
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
129,Yönetim Bilişim Sistemleri (İÖ),YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,63
130,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,24
131,Yönetim Bilişim Sistemleri (İÖ),YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,31
132,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,59
133,Yönetim Bilişim Sistemleri (İÖ),YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,62

In [106]:
allowed = ["KPD 102", "FİZ 176", "CSE 102L", "CSE 392"]

df.drop(
    index=df[
        (df['KREDI'] == 1) & (~df['CourseCode'].isin(allowed))
    ].index,
    inplace=True
)

In [107]:
drop_cols = ['FacultyName', 'FacultyCode', 'DepartmentCode', 'CourseId', 'AKTS', 'DERS_ID', 'DONEM_TIP']
df.drop(labels=drop_cols, inplace=True, axis=1)
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,Örgün Eğitim,1,3,0,4,2,1,S,4205238,6
1,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,Örgün Eğitim,1,3,1,4,2,0,S,4419464,9
2,Makine Mühendisliği,TDB 115,Akademik Türkçe,Örgün Eğitim,1,3,0,1,3,0,S,2615883,1
3,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,S,1666337,15
4,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,Örgün Eğitim,1,4,0,3,4,0,Z,2576518,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,Örgün Eğitim,1,4,0,2,3,1,Z,2446060,13
529,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,2,0,4,2,0,S,2832797,14
530,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,3,0,4,3,0,S,3473810,39
531,Elektrik-Elektronik Mühendisliği (İÖ),EEE 499,Yenilenebilir Enerji Kaynakları,2.Öğretim,1,3,0,4,3,0,S,3473810,42
532,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,Örgün Eğitim,1,4,0,3,3,1,Z,2977082,125

In [4]:
df["DepartmentName"] = (
    df["DepartmentName"]
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()                                
)

deps = df["DepartmentName"].unique()
deps

array(['Finans ve Bankacılık', 'Pazarlama', 'Sigortacılık',
       'Uluslararası Ticaret ve Lojistik', 'Yönetim Bilişim Sistemleri'],
      dtype=object)

In [109]:
df["DepartmentName"] = df["DepartmentName"].replace(
    {"Yapay Zeka ve Veri Mühendisliği": "Bilgisayar Mühendisliği"}
)

In [6]:
remove_codes = ["ATA 102", "TDB 102", "TDP 100", "TDP 304", "YBD 102", "YBD 104"]
df.drop(
    index=df[
        #df["CourseCode"].isin(remove_codes) |
        df["CourseCode"].str.contains("HOBİ", na=False) |
        df["CourseCode"].str.contains("ATA", na=False) |
        df["CourseCode"].str.contains("TDB", na=False) |
        # df["CourseCode"].str.contains("TDP", na=False) |
        df["CourseCode"].str.contains("YBD", na=False)
        # df["CourseCode"].str.contains("PFE", na=False)
    ].index,
    inplace=True
)
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
129,Yönetim Bilişim Sistemleri,YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,63
130,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,24
131,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,31
132,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,59
133,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,62

In [7]:

for dep in deps:
    codes = df[df["DepartmentName"] == dep]["CourseCode"].unique()
    for code in codes:
        # Filter the rows with the same DepartmentName and CourseCode
        courses = df[(df["DepartmentName"] == dep) & (df["CourseCode"] == code)]
        if len(courses) > 1:
            sum_count = courses["OgrenciSayisi"].sum()
            
            # Keep the first index, drop the rest
            keep_index = courses.index[0]
            drop_indices = courses.index[1:]
            
            df.loc[keep_index, "OgrenciSayisi"] = sum_count
            df.drop(drop_indices, inplace=True)

# Reset index if necessary
df.reset_index(drop=True, inplace=True)

In [8]:
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
99,Yönetim Bilişim Sistemleri,YBS 356,Yöneylem Araştırması II,5,3,0,3,Z,1450512,190
100,Yönetim Bilişim Sistemleri,YBS 358,Finansal Yönetim,5,3,0,3,Z,2550322,161
101,Yönetim Bilişim Sistemleri,YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,132
102,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,55
103,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,121

In [9]:
#df2 = pd.read_excel("./course_data.xlsx")
df2 = pd.read_excel("./UBF_course_data_RAW.xlsx")
df2

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
129,Yönetim Bilişim Sistemleri (İÖ),YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,63
130,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,24
131,Yönetim Bilişim Sistemleri (İÖ),YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,31
132,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,59
133,Yönetim Bilişim Sistemleri (İÖ),YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,62

In [10]:
diff = df[~df['CourseCode'].isin(df2['CourseCode'])]
diff

Empty DataFrame
Columns: [DepartmentName, CourseCode, CourseName, AKTS, KREDI, Lab, SINIF, ZOR_SEC, InstructorUserId, OgrenciSayisi]
Index: []

In [11]:
diff2 = df2[~df2['CourseCode'].isin(df['CourseCode'])]
diff2

Empty DataFrame
Columns: [DepartmentName, CourseCode, CourseName, AKTS, KREDI, Lab, SINIF, ZOR_SEC, InstructorUserId, OgrenciSayisi]
Index: []

In [12]:
df = df.drop(index=diff.index).reset_index(drop=True)
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
99,Yönetim Bilişim Sistemleri,YBS 356,Yöneylem Araştırması II,5,3,0,3,Z,1450512,190
100,Yönetim Bilişim Sistemleri,YBS 358,Finansal Yönetim,5,3,0,3,Z,2550322,161
101,Yönetim Bilişim Sistemleri,YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,132
102,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,55
103,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,121

In [13]:
df["Lab"] = 0
lab_codes = df2.loc[df2["Lab"] == 1, "CourseCode"]
df.loc[df["CourseCode"].isin(lab_codes), "Lab"] = 1
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
99,Yönetim Bilişim Sistemleri,YBS 356,Yöneylem Araştırması II,5,3,0,3,Z,1450512,190
100,Yönetim Bilişim Sistemleri,YBS 358,Finansal Yönetim,5,3,0,3,Z,2550322,161
101,Yönetim Bilişim Sistemleri,YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,132
102,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,55
103,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,121

In [14]:
df

,DepartmentName,CourseCode,CourseName,AKTS,KREDI,Lab,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Finans ve Bankacılık,BAF104,İktisat II,5,3,0,1,Z,3750338,96
1,Finans ve Bankacılık,BAF106,Muhasebe II,5,3,0,1,Z,2750113,107
2,Finans ve Bankacılık,BAF108,Finans Matematiği,4,3,0,1,Z,2400356,114
3,Finans ve Bankacılık,BAF110,Borçlar Hukuku,4,3,0,1,Z,4565554,99
4,Finans ve Bankacılık,BAF202,Banka Muhasebesi,5,3,0,2,Z,2540145,64
...,...,...,...,...,...,...,...,...,...,...
99,Yönetim Bilişim Sistemleri,YBS 356,Yöneylem Araştırması II,5,3,0,3,Z,1450512,190
100,Yönetim Bilişim Sistemleri,YBS 358,Finansal Yönetim,5,3,0,3,Z,2550322,161
101,Yönetim Bilişim Sistemleri,YBS 384,Bilgisayar Tabanlı Optimizasyon,5,3,0,3,S,5564242,132
102,Yönetim Bilişim Sistemleri,YBS 386,Veri İletişimi ve Bilgisayar Ağları,5,3,0,3,S,2565028,55
103,Yönetim Bilişim Sistemleri,YBS 388,Kalite Yönetim Sistemleri,5,3,0,3,S,3668244,121

In [15]:
df.to_excel("./UBF_course_data.xlsx", index=False, header=True)

Lab saatlerini uygulamaya yaz