In [10]:
import pandas as pd

In [31]:
df = pd.read_excel("./BerkDataRAW.xlsx")
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,6287177,Örgün Eğitim,1,6,6287177,Bahar,4,0,2,3,2,Z,3435711,26
1,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,6287180,Örgün Eğitim,2,6,6287180,Bahar,4,0,2,3,2,Z,3435711,40
2,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 336,Advanced Web Programming,6287191,Örgün Eğitim,1,6,6287191,Bahar,4,0,3,3,1,S,2107934,12
3,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,6285587,Örgün Eğitim,1,4,6285587,Bahar,3,0,2,2,1,Z,3048102,125
4,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,6269432,Örgün Eğitim,1,5,6269432,Bahar,3,0,2,2,1,Z,1098471,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,6269457,Örgün Eğitim,1,5,6269457,Bahar,3,0,4,2,1,Z,5997408,9
505,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,6287142,Örgün Eğitim,1,5,6287142,Bahar,3,0,4,2,1,S,3524624,15
506,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,6269440,Örgün Eğitim,1,5,6269440,Bahar,4,0,3,3,1,Z,1892200,2
507,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,6269440,Örgün Eğitim,1,5,6269440,Bahar,4,0,3,3,1,Z,1892200,5
508,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,6287105,Örgün Eğitim,1,5,6287105,Bahar,3,0,3,2,1,S,2977082,52

In [32]:
df.drop(index=df[df['KREDI'] == 0].index, inplace=True)
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,6287177,Örgün Eğitim,1,6,6287177,Bahar,4,0,2,3,2,Z,3435711,26
1,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,6287180,Örgün Eğitim,2,6,6287180,Bahar,4,0,2,3,2,Z,3435711,40
2,Mühendislik Fakültesi,8,1040,Bilgisayar Mühendisliği (İngilizce),CSE 336,Advanced Web Programming,6287191,Örgün Eğitim,1,6,6287191,Bahar,4,0,3,3,1,S,2107934,12
3,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,6285587,Örgün Eğitim,1,4,6285587,Bahar,3,0,2,2,1,Z,3048102,125
4,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,6269432,Örgün Eğitim,1,5,6269432,Bahar,3,0,2,2,1,Z,1098471,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,6269457,Örgün Eğitim,1,5,6269457,Bahar,3,0,4,2,1,Z,5997408,9
505,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,6287142,Örgün Eğitim,1,5,6287142,Bahar,3,0,4,2,1,S,3524624,15
506,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,6269440,Örgün Eğitim,1,5,6269440,Bahar,4,0,3,3,1,Z,1892200,2
507,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,6269440,Örgün Eğitim,1,5,6269440,Bahar,4,0,3,3,1,Z,1892200,5
508,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,6287105,Örgün Eğitim,1,5,6287105,Bahar,3,0,3,2,1,S,2977082,52

In [33]:
drop_cols = ['FacultyName', 'FacultyCode', 'DepartmentCode', 'CourseId', 'AKTS', 'DERS_ID', 'DONEM_TIP']
df.drop(labels=drop_cols, inplace=True, axis=1)
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,Örgün Eğitim,1,4,0,2,3,2,Z,3435711,26
1,Bilgisayar Mühendisliği (İngilizce),CSE 214,Advanced Application Development,Örgün Eğitim,2,4,0,2,3,2,Z,3435711,40
2,Bilgisayar Mühendisliği (İngilizce),CSE 336,Advanced Web Programming,Örgün Eğitim,1,4,0,3,3,1,S,2107934,12
3,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,3048102,125
4,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,1098471,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,Örgün Eğitim,1,3,0,4,2,1,Z,5997408,9
505,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,Örgün Eğitim,1,3,0,4,2,1,S,3524624,15
506,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,Örgün Eğitim,1,4,0,3,3,1,Z,1892200,2
507,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,Örgün Eğitim,1,4,0,3,3,1,Z,1892200,5
508,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,Örgün Eğitim,1,3,0,3,2,1,S,2977082,52

In [34]:
df["DepartmentName"] = (
    df["DepartmentName"]
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()                                
)

deps = df["DepartmentName"].unique()
deps

array(['Bilgisayar Mühendisliği', 'İnşaat Mühendisliği',
       'Jeoloji Mühendisliği', 'Gıda Mühendisliği',
       'Elektrik-Elektronik Mühendisliği', 'Makine Mühendisliği',
       'Çevre Mühendisliği', 'Yapay Zeka ve Veri Mühendisliği'],
      dtype=object)

In [35]:

for dep in deps:
    codes = df[df["DepartmentName"] == dep]["CourseCode"].unique()
    for code in codes:
        # Filter the rows with the same DepartmentName and CourseCode
        courses = df[(df["DepartmentName"] == dep) & (df["CourseCode"] == code)]
        if len(courses) > 1:
            sum_count = courses["OgrenciSayisi"].sum()
            
            # Keep the first index, drop the rest
            keep_index = courses.index[0]
            drop_indices = courses.index[1:]
            
            df.loc[keep_index, "OgrenciSayisi"] = sum_count
            df.drop(drop_indices, inplace=True)

# Reset index if necessary
df.reset_index(drop=True, inplace=True)

In [37]:
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Bilgisayar Mühendisliği,CSE 214,Advanced Application Development,Örgün Eğitim,1,4,0,2,3,2,Z,3435711,66
1,Bilgisayar Mühendisliği,CSE 336,Advanced Web Programming,Örgün Eğitim,1,4,0,3,3,1,S,2107934,12
2,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,3048102,125
3,Jeoloji Mühendisliği,JEO 202,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,1098471,7
4,Gıda Mühendisliği,GIDA 224,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,3,0,Z,2061533,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,Jeoloji Mühendisliği,JEO 408,Yeraltı Jeolojisi,Örgün Eğitim,1,3,0,4,2,1,Z,5997408,9
289,İnşaat Mühendisliği,İNM 476,Yüksek Yapılar,Örgün Eğitim,1,3,0,4,2,1,S,3524624,15
290,İnşaat Mühendisliği,JEO 308,Zemin Mekaniği,Örgün Eğitim,1,4,0,3,3,1,Z,1892200,2
291,Jeoloji Mühendisliği,JEO 308,Zemin Mekaniği,Örgün Eğitim,1,4,0,3,3,1,Z,1892200,5
292,İnşaat Mühendisliği,İNM 360,Zemin Mekaniği 2,Örgün Eğitim,1,3,0,3,2,1,S,2977082,52

In [38]:
df.to_excel("./BerkData3RAW.xlsx", index=False, header=True)

Lab saatlerini uygulamaya yaz