In [72]:
import pandas as pd

In [73]:
df = pd.read_excel("./BerkDataRAW.xlsx")
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,6285587,Örgün Eğitim,1,4,6285587,Bahar,3,0,2,2,1,Z,3048102,125
1,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,ATA 102,Atatürk İlkeleri ve İnkılap Tarihi II,6285584,Örgün Eğitim,1,2,6285584,Bahar,2,0,2,2,0,Z,1145553,71
2,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 302,Betonarme 2,6287097,Örgün Eğitim,1,5,6287097,Bahar,4,0,3,3,1,Z,2669297,50
3,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 302,Betonarme 2,6287098,Örgün Eğitim,2,5,6287098,Bahar,4,0,3,3,1,Z,5213213,55
4,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 352,Bilgisayar Destekli Yapı Analizi,6287103,Örgün Eğitim,1,5,6287103,Bahar,3,0,3,2,1,S,2669297,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),KPD 102,Kariyer Planlama,6287162,Örgün Eğitim,1,2,6287162,Bahar,1,0,1,1,0,Z,1267061,7
505,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),MAT 152,Mathematics II,6287163,Örgün Eğitim,1,6,6287163,Bahar,5,0,1,4,2,Z,4828331,7
506,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 174,Physics II,6287160,Örgün Eğitim,1,4,6287160,Bahar,3,0,1,3,0,Z,5320332,7
507,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 176,Physics II Laboratory,6287161,Örgün Eğitim,1,2,6287161,Bahar,1,0,1,0,2,Z,5320332,7
508,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),TDB 102,Türk Dili II,6282338,Örgün Eğitim,1,2,6282338,Bahar,2,0,1,2,0,Z,2692386,7

In [74]:
df.drop(index=df[df['KREDI'] == 0].index, inplace=True)
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,6285587,Örgün Eğitim,1,4,6285587,Bahar,3,0,2,2,1,Z,3048102,125
1,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,ATA 102,Atatürk İlkeleri ve İnkılap Tarihi II,6285584,Örgün Eğitim,1,2,6285584,Bahar,2,0,2,2,0,Z,1145553,71
2,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 302,Betonarme 2,6287097,Örgün Eğitim,1,5,6287097,Bahar,4,0,3,3,1,Z,2669297,50
3,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 302,Betonarme 2,6287098,Örgün Eğitim,2,5,6287098,Bahar,4,0,3,3,1,Z,5213213,55
4,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 352,Bilgisayar Destekli Yapı Analizi,6287103,Örgün Eğitim,1,5,6287103,Bahar,3,0,3,2,1,S,2669297,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),KPD 102,Kariyer Planlama,6287162,Örgün Eğitim,1,2,6287162,Bahar,1,0,1,1,0,Z,1267061,7
505,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),MAT 152,Mathematics II,6287163,Örgün Eğitim,1,6,6287163,Bahar,5,0,1,4,2,Z,4828331,7
506,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 174,Physics II,6287160,Örgün Eğitim,1,4,6287160,Bahar,3,0,1,3,0,Z,5320332,7
507,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 176,Physics II Laboratory,6287161,Örgün Eğitim,1,2,6287161,Bahar,1,0,1,0,2,Z,5320332,7
508,Mühendislik Fakültesi,8,10662,Yapay Zeka ve Veri Mühendisliği (İngilizce),TDB 102,Türk Dili II,6282338,Örgün Eğitim,1,2,6282338,Bahar,2,0,1,2,0,Z,2692386,7

In [75]:
allowed = ["KPD 102", "FİZ 176", "CSE 102L"]

df.drop(
    index=df[
        (df['KREDI'] == 1) & (~df['CourseCode'].isin(allowed))
    ].index,
    inplace=True
)

In [76]:
drop_cols = ['FacultyName', 'FacultyCode', 'DepartmentCode', 'CourseId', 'AKTS', 'DERS_ID', 'DONEM_TIP']
df.drop(labels=drop_cols, inplace=True, axis=1)
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,3048102,125
1,İnşaat Mühendisliği,ATA 102,Atatürk İlkeleri ve İnkılap Tarihi II,Örgün Eğitim,1,2,0,2,2,0,Z,1145553,71
2,İnşaat Mühendisliği,İNM 302,Betonarme 2,Örgün Eğitim,1,4,0,3,3,1,Z,2669297,50
3,İnşaat Mühendisliği,İNM 302,Betonarme 2,Örgün Eğitim,2,4,0,3,3,1,Z,5213213,55
4,İnşaat Mühendisliği,İNM 352,Bilgisayar Destekli Yapı Analizi,Örgün Eğitim,1,3,0,3,2,1,S,2669297,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Yapay Zeka ve Veri Mühendisliği (İngilizce),KPD 102,Kariyer Planlama,Örgün Eğitim,1,1,0,1,1,0,Z,1267061,7
505,Yapay Zeka ve Veri Mühendisliği (İngilizce),MAT 152,Mathematics II,Örgün Eğitim,1,5,0,1,4,2,Z,4828331,7
506,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 174,Physics II,Örgün Eğitim,1,3,0,1,3,0,Z,5320332,7
507,Yapay Zeka ve Veri Mühendisliği (İngilizce),FİZ 176,Physics II Laboratory,Örgün Eğitim,1,1,0,1,0,2,Z,5320332,7
508,Yapay Zeka ve Veri Mühendisliği (İngilizce),TDB 102,Türk Dili II,Örgün Eğitim,1,2,0,1,2,0,Z,2692386,7

In [77]:
df["DepartmentName"] = (
    df["DepartmentName"]
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()                                
)

deps = df["DepartmentName"].unique()
deps

array(['İnşaat Mühendisliği', 'Çevre Mühendisliği', 'Makine Mühendisliği',
       'Jeoloji Mühendisliği', 'Elektrik-Elektronik Mühendisliği',
       'Gıda Mühendisliği', 'Bilgisayar Mühendisliği',
       'Yapay Zeka ve Veri Mühendisliği'], dtype=object)

In [78]:
df["DepartmentName"] = df["DepartmentName"].replace(
    {"Yapay Zeka ve Veri Mühendisliği": "Bilgisayar Mühendisliği"}
)

In [79]:
remove_codes = ["ATA 102", "TDB 102", "TDP 100", "TDP 304", "YBD 102", "YBD 104"]
df.drop(
    index=df[
        df["CourseCode"].isin(remove_codes) |
        df["CourseCode"].str.contains("HOBİ", na=False) |
        df["CourseCode"].str.contains("PFE", na=False)
    ].index,
    inplace=True
)

In [80]:

for dep in deps:
    codes = df[df["DepartmentName"] == dep]["CourseCode"].unique()
    for code in codes:
        # Filter the rows with the same DepartmentName and CourseCode
        courses = df[(df["DepartmentName"] == dep) & (df["CourseCode"] == code)]
        if len(courses) > 1:
            sum_count = courses["OgrenciSayisi"].sum()
            
            # Keep the first index, drop the rest
            keep_index = courses.index[0]
            drop_indices = courses.index[1:]
            
            df.loc[keep_index, "OgrenciSayisi"] = sum_count
            df.drop(drop_indices, inplace=True)

# Reset index if necessary
df.reset_index(drop=True, inplace=True)

In [81]:
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,3048102,125
1,İnşaat Mühendisliği,İNM 302,Betonarme 2,Örgün Eğitim,1,4,0,3,3,1,Z,2669297,105
2,İnşaat Mühendisliği,İNM 352,Bilgisayar Destekli Yapı Analizi,Örgün Eğitim,1,3,0,3,2,1,S,2669297,69
3,İnşaat Mühendisliği,İNM 104,Bilgisayar Programlama,Örgün Eğitim,1,3,0,1,2,1,Z,1684669,74
4,İnşaat Mühendisliği,İNM 304,Çelik Yapılar,Örgün Eğitim,1,4,0,3,3,1,Z,1318658,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Bilgisayar Mühendisliği,CSE 434,Programming Languages,Örgün Eğitim,1,4,0,4,3,1,S,2903204,51
230,Bilgisayar Mühendisliği,CSE 182,Rhetoric and Argumentation,Örgün Eğitim,1,2,0,1,2,0,Z,1616504,3
231,Bilgisayar Mühendisliği,CSE 408,Scientific Programming,Örgün Eğitim,1,4,0,4,3,1,S,7248701,44
232,Bilgisayar Mühendisliği,CSE 474,Social Network Analysis,Örgün Eğitim,1,4,0,4,3,1,S,3435711,42
233,Bilgisayar Mühendisliği,CSE 332,Software Engineering,Örgün Eğitim,1,4,0,3,3,2,Z,1267061,102

In [82]:
df.to_excel("./BerkData4RAW.xlsx", index=False, header=True)

Lab saatlerini uygulamaya yaz