In [103]:
import pandas as pd

In [104]:
df = pd.read_excel("./25-26Fall.xlsx")
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,6317538,Örgün Eğitim,1,5,6317538,Güz,3,0,4,2,1,S,4205238,6
1,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,6317540,Örgün Eğitim,1,5,6317540,Güz,3,1,4,2,0,S,4419464,9
2,Mühendislik Fakültesi,8,37,Makine Mühendisliği,TDB 115,Akademik Türkçe,6317698,Örgün Eğitim,1,5,6317698,Güz,3,0,1,3,0,S,2615883,1
3,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,6317652,Örgün Eğitim,1,3,6317652,Güz,3,0,2,2,1,S,1666337,15
4,Mühendislik Fakültesi,8,37,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,6357316,Örgün Eğitim,1,6,6357316,Güz Öncesi Tek Ders,4,0,3,4,0,Z,2576518,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,6322615,Örgün Eğitim,1,5,6322615,Güz,4,0,2,3,1,Z,2446060,13
529,Mühendislik Fakültesi,8,37,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,6323242,Örgün Eğitim,1,3,6323242,Güz,2,0,4,2,0,S,2832797,14
530,Mühendislik Fakültesi,8,39,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,6346720,Örgün Eğitim,1,5,6346720,Güz,3,0,4,3,0,S,3473810,39
531,Mühendislik Fakültesi,8,808,Elektrik-Elektronik Mühendisliği (İÖ),EEE 499,Yenilenebilir Enerji Kaynakları,6346758,2.Öğretim,1,5,6346758,Güz,3,0,4,3,0,S,3473810,42
532,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,6324548,Örgün Eğitim,1,5,6324548,Güz,4,0,3,3,1,Z,2977082,125

In [105]:
df.drop(index=df[df['KREDI'] == 0].index, inplace=True)
df

,FacultyName,FacultyCode,DepartmentCode,DepartmentName,CourseCode,CourseName,CourseId,EducationType,CourseSectionCode,AKTS,DERS_ID,DONEM_TIP,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,6317538,Örgün Eğitim,1,5,6317538,Güz,3,0,4,2,1,S,4205238,6
1,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,6317540,Örgün Eğitim,1,5,6317540,Güz,3,1,4,2,0,S,4419464,9
2,Mühendislik Fakültesi,8,37,Makine Mühendisliği,TDB 115,Akademik Türkçe,6317698,Örgün Eğitim,1,5,6317698,Güz,3,0,1,3,0,S,2615883,1
3,Mühendislik Fakültesi,8,36,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,6317652,Örgün Eğitim,1,3,6317652,Güz,3,0,2,2,1,S,1666337,15
4,Mühendislik Fakültesi,8,37,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,6357316,Örgün Eğitim,1,6,6357316,Güz Öncesi Tek Ders,4,0,3,4,0,Z,2576518,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Mühendislik Fakültesi,8,38,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,6322615,Örgün Eğitim,1,5,6322615,Güz,4,0,2,3,1,Z,2446060,13
529,Mühendislik Fakültesi,8,37,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,6323242,Örgün Eğitim,1,3,6323242,Güz,2,0,4,2,0,S,2832797,14
530,Mühendislik Fakültesi,8,39,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,6346720,Örgün Eğitim,1,5,6346720,Güz,3,0,4,3,0,S,3473810,39
531,Mühendislik Fakültesi,8,808,Elektrik-Elektronik Mühendisliği (İÖ),EEE 499,Yenilenebilir Enerji Kaynakları,6346758,2.Öğretim,1,5,6346758,Güz,3,0,4,3,0,S,3473810,42
532,Mühendislik Fakültesi,8,35,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,6324548,Örgün Eğitim,1,5,6324548,Güz,4,0,3,3,1,Z,2977082,125

In [106]:
allowed = ["KPD 102", "FİZ 176", "CSE 102L", "CSE 392"]

df.drop(
    index=df[
        (df['KREDI'] == 1) & (~df['CourseCode'].isin(allowed))
    ].index,
    inplace=True
)

In [107]:
drop_cols = ['FacultyName', 'FacultyCode', 'DepartmentCode', 'CourseId', 'AKTS', 'DERS_ID', 'DONEM_TIP']
df.drop(labels=drop_cols, inplace=True, axis=1)
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,Örgün Eğitim,1,3,0,4,2,1,S,4205238,6
1,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,Örgün Eğitim,1,3,1,4,2,0,S,4419464,9
2,Makine Mühendisliği,TDB 115,Akademik Türkçe,Örgün Eğitim,1,3,0,1,3,0,S,2615883,1
3,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,S,1666337,15
4,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,Örgün Eğitim,1,4,0,3,4,0,Z,2576518,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,Örgün Eğitim,1,4,0,2,3,1,Z,2446060,13
529,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,2,0,4,2,0,S,2832797,14
530,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,3,0,4,3,0,S,3473810,39
531,Elektrik-Elektronik Mühendisliği (İÖ),EEE 499,Yenilenebilir Enerji Kaynakları,2.Öğretim,1,3,0,4,3,0,S,3473810,42
532,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,Örgün Eğitim,1,4,0,3,3,1,Z,2977082,125

In [108]:
df["DepartmentName"] = (
    df["DepartmentName"]
    .str.replace(r'\s*\(.*?\)', '', regex=True)
    .str.strip()                                
)

deps = df["DepartmentName"].unique()
deps

array(['Çevre Mühendisliği', 'Makine Mühendisliği',
       'Bilgisayar Mühendisliği', 'Gıda Mühendisliği',
       'Jeoloji Mühendisliği', 'Elektrik-Elektronik Mühendisliği',
       'Yapay Zeka ve Veri Mühendisliği', 'İnşaat Mühendisliği'],
      dtype=object)

In [109]:
df["DepartmentName"] = df["DepartmentName"].replace(
    {"Yapay Zeka ve Veri Mühendisliği": "Bilgisayar Mühendisliği"}
)

In [110]:
remove_codes = ["ATA 102", "TDB 102", "TDP 100", "TDP 304", "YBD 102", "YBD 104"]
df.drop(
    index=df[
        #df["CourseCode"].isin(remove_codes) |
        df["CourseCode"].str.contains("HOBİ", na=False) |
        df["CourseCode"].str.contains("ATA", na=False) |
        df["CourseCode"].str.contains("TDB", na=False) |
        df["CourseCode"].str.contains("TDP", na=False) |
        df["CourseCode"].str.contains("YBD", na=False) |
        df["CourseCode"].str.contains("PFE", na=False)
    ].index,
    inplace=True
)

In [111]:

for dep in deps:
    codes = df[df["DepartmentName"] == dep]["CourseCode"].unique()
    for code in codes:
        # Filter the rows with the same DepartmentName and CourseCode
        courses = df[(df["DepartmentName"] == dep) & (df["CourseCode"] == code)]
        if len(courses) > 1:
            sum_count = courses["OgrenciSayisi"].sum()
            
            # Keep the first index, drop the rest
            keep_index = courses.index[0]
            drop_indices = courses.index[1:]
            
            df.loc[keep_index, "OgrenciSayisi"] = sum_count
            df.drop(drop_indices, inplace=True)

# Reset index if necessary
df.reset_index(drop=True, inplace=True)

In [112]:
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,Örgün Eğitim,1,3,0,4,2,1,S,4205238,6
1,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,Örgün Eğitim,1,3,1,4,2,0,S,4419464,9
2,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,S,1666337,15
3,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,Örgün Eğitim,1,4,0,3,4,0,Z,2576518,105
4,Bilgisayar Mühendisliği,CSE 301,Algorithms,Örgün Eğitim,1,5,0,3,4,1,Z,7248701,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,İnşaat Mühendisliği,İNM 467,Yapıların Yalıtımı ve Korunması,Örgün Eğitim,1,3,0,4,2,1,S,1021641,23
235,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,Örgün Eğitim,1,4,0,2,3,1,Z,2446060,13
236,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,2,0,4,2,0,S,2832797,14
237,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,3,0,4,3,0,S,3473810,81
238,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,Örgün Eğitim,1,4,0,3,3,1,Z,2977082,125

In [113]:
df2 = pd.read_excel("./course_data.xlsx")
df2

,DepartmentName,CourseCode,CourseName,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi,Lab
0,Çevre Mühendisliği,ÇEV 102,Çevre Ekolojisi,1,Z,3979315,19,0
1,Çevre Mühendisliği,ÇEV 108,Statik ve Mukavemet,1,S,1098471,19,0
2,Çevre Mühendisliği,ÇEV 156,Computer Programming,1,Z,1307360,18,1
3,Çevre Mühendisliği,ÇEV 160,Analytical Chemistry,1,S,2719999,22,0
4,Çevre Mühendisliği,ÇEV 162,Physics II,1,S,1830239,18,0
...,...,...,...,...,...,...,...,...
221,Jeoloji Mühendisliği,MAT 162,Matematik 2,1,Z,2550816,15,0
222,Gıda Mühendisliği,MAT 162,Matematik II,1,Z,4117613,99,0
223,Makine Mühendisliği,MAT 162,Matematik II,1,Z,1739868,159,0
224,Bilgisayar Mühendisliği,MAT 222,Linear Algebra,2,Z,4693090,135,0
225,Makine Mühendisliği,MTH 404,Havacılık Yapısalları İmalat Teknikleri,4,S,1210302,34,0

In [114]:
diff = df[~df['CourseCode'].isin(df2['CourseCode'])]
diff

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,Örgün Eğitim,1,3,0,4,2,1,S,4205238,6
1,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,Örgün Eğitim,1,3,1,4,2,0,S,4419464,9
2,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,S,1666337,15
3,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,Örgün Eğitim,1,4,0,3,4,0,Z,2576518,105
4,Bilgisayar Mühendisliği,CSE 301,Algorithms,Örgün Eğitim,1,5,0,3,4,1,Z,7248701,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,İnşaat Mühendisliği,İNM 467,Yapıların Yalıtımı ve Korunması,Örgün Eğitim,1,3,0,4,2,1,S,1021641,23
235,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,Örgün Eğitim,1,4,0,2,3,1,Z,2446060,13
236,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,2,0,4,2,0,S,2832797,14
237,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,3,0,4,3,0,S,3473810,81
238,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,Örgün Eğitim,1,4,0,3,3,1,Z,2977082,125

In [115]:
diff2 = df2[~df2['CourseCode'].isin(df['CourseCode'])]
diff2

,DepartmentName,CourseCode,CourseName,SINIF,ZOR_SEC,InstructorUserId,OgrenciSayisi,Lab
0,Çevre Mühendisliği,ÇEV 102,Çevre Ekolojisi,1,Z,3979315,19,0
1,Çevre Mühendisliği,ÇEV 108,Statik ve Mukavemet,1,S,1098471,19,0
2,Çevre Mühendisliği,ÇEV 156,Computer Programming,1,Z,1307360,18,1
3,Çevre Mühendisliği,ÇEV 160,Analytical Chemistry,1,S,2719999,22,0
4,Çevre Mühendisliği,ÇEV 162,Physics II,1,S,1830239,18,0
...,...,...,...,...,...,...,...,...
221,Jeoloji Mühendisliği,MAT 162,Matematik 2,1,Z,2550816,15,0
222,Gıda Mühendisliği,MAT 162,Matematik II,1,Z,4117613,99,0
223,Makine Mühendisliği,MAT 162,Matematik II,1,Z,1739868,159,0
224,Bilgisayar Mühendisliği,MAT 222,Linear Algebra,2,Z,4693090,135,0
225,Makine Mühendisliği,MTH 404,Havacılık Yapısalları İmalat Teknikleri,4,S,1210302,34,0

In [102]:
df = df.drop(index=diff.index).reset_index(drop=True)
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,İnşaat Mühendisliği,İNM 304,Çelik Yapılar,Örgün Eğitim,1,4,0,3,3,1,Z,1318658,1
1,Gıda Mühendisliği,FİZ 168,Fizik II,Örgün Eğitim,1,3,0,1,2,2,Z,3496303,1
2,Elektrik-Elektronik Mühendisliği,EEM 350,Otomatik Kontrol,Örgün Eğitim,1,4,0,3,4,0,Z,4721220,1
3,Elektrik-Elektronik Mühendisliği,EEM 304,Power Electronics,2.Öğretim,1,3,0,3,3,0,S,1029126,2
4,Bilgisayar Mühendisliği,CSE 332,Software Engineering,Örgün Eğitim,1,4,0,3,3,2,Z,1267061,1
5,Çevre Mühendisliği,ÇEV 210,Termodinamik,Örgün Eğitim,1,3,0,2,3,0,S,4205238,1

In [74]:
df["Lab"] = 0
lab_codes = df2.loc[df2["Lab"] == 1, "CourseCode"]
df.loc[df["CourseCode"].isin(lab_codes), "Lab"] = 1
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi,Lab
0,İnşaat Mühendisliği,İNM 206,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,Z,3048102,125,0
1,İnşaat Mühendisliği,İNM 302,Betonarme 2,Örgün Eğitim,1,4,0,3,3,1,Z,2669297,105,0
2,İnşaat Mühendisliği,İNM 352,Bilgisayar Destekli Yapı Analizi,Örgün Eğitim,1,3,0,3,2,1,S,2669297,69,1
3,İnşaat Mühendisliği,İNM 104,Bilgisayar Programlama,Örgün Eğitim,1,3,0,1,2,1,Z,1684669,74,1
4,İnşaat Mühendisliği,İNM 304,Çelik Yapılar,Örgün Eğitim,1,4,0,3,3,1,Z,1318658,97,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Bilgisayar Mühendisliği,CSE 434,Programming Languages,Örgün Eğitim,1,4,0,4,3,1,S,2903204,51,0
227,Bilgisayar Mühendisliği,CSE 408,Scientific Programming,Örgün Eğitim,1,4,0,4,3,1,S,7248701,44,1
228,Bilgisayar Mühendisliği,CSE 392,Seminar,Örgün Eğitim,1,1,0,3,0,2,Z,3143825,84,1
229,Bilgisayar Mühendisliği,CSE 474,Social Network Analysis,Örgün Eğitim,1,4,0,4,3,1,S,3435711,42,0
230,Bilgisayar Mühendisliği,CSE 332,Software Engineering,Örgün Eğitim,1,4,0,3,3,2,Z,1267061,102,1

In [116]:
df

,DepartmentName,CourseCode,CourseName,EducationType,CourseSectionCode,KREDI,LAB_SAAT,SINIF,TEO_SAAT,UYG_SAAT,ZOR_SEC,InstructorUserId,OgrenciSayisi
0,Çevre Mühendisliği,ÇEV 457,Air Pollution Control,Örgün Eğitim,1,3,0,4,2,1,S,4205238,6
1,Çevre Mühendisliği,ÇEV 461,Air Pollution Modelling,Örgün Eğitim,1,3,1,4,2,0,S,4419464,9
2,Çevre Mühendisliği,ÇEV 207,Akışkanlar Mekaniği,Örgün Eğitim,1,3,0,2,2,1,S,1666337,15
3,Makine Mühendisliği,MAK 307,Akışkanlar Mekaniği,Örgün Eğitim,1,4,0,3,4,0,Z,2576518,105
4,Bilgisayar Mühendisliği,CSE 301,Algorithms,Örgün Eğitim,1,5,0,3,4,1,Z,7248701,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,İnşaat Mühendisliği,İNM 467,Yapıların Yalıtımı ve Korunması,Örgün Eğitim,1,3,0,4,2,1,S,1021641,23
235,Jeoloji Mühendisliği,JEO 209,Yapısal Jeoloji,Örgün Eğitim,1,4,0,2,3,1,Z,2446060,13
236,Makine Mühendisliği,MAK 471,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,2,0,4,2,0,S,2832797,14
237,Elektrik-Elektronik Mühendisliği,EEE 499,Yenilenebilir Enerji Kaynakları,Örgün Eğitim,1,3,0,4,3,0,S,3473810,81
238,İnşaat Mühendisliği,İNM 301,Zemin Mekaniği 1,Örgün Eğitim,1,4,0,3,3,1,Z,2977082,125

In [117]:
df.to_excel("./course_data3.xlsx", index=False, header=True)

Lab saatlerini uygulamaya yaz